# Generated by Django 3.2 on 2022-12-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО учителя')),
                ('class_name', models.CharField(choices=[('a_class', 'a_class'), ('b_class', 'b_class'), ('c_class', 'c_class')], max_length=20, verbose_name='Название класса')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО школьника')),
                ('birth_date', models.DateField(verbose_name='Дата рождения школьника')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_school.teacher')),
            ],
        ),
    ]
